include:
  - project: 'globalid/infrastructure/gitlab-ci'
    ref: master
    file:
      - '/templates/java-lib-current.yml'

test:
  stage: test
  variables:
    QUARKUS_EDA_RABBIT_HOST: rabbitmq
  script:
    - mvn -s $MAVEN_SETTINGS $MAVEN_CLI_OPTS verify -Dci=$CI_JOB_ID
  services:
    - name: rabbitmq:3-alpine
      alias: rabbitmq
