name: Create release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: false
        default: ''
jobs:
  release:
    name: Release
    uses: globalid/.github/.github/workflows/maven-release.yml@master
    with:
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
    secrets: inherit
