name: Build & test
"on":
  push:
    branches:
      - '*'
    tags:
      - v*
  workflow_dispatch: null
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup java
        uses: globalid/github-actions/java-setup@main
        with:
          nexus-username: "${{ secrets.NEXUS_USERNAME }}"
          nexus-password: "${{ secrets.NEXUS_PASSWORD }}"
      - shell: sh
        run: "mvn  verify -Dci=${{ github.run_id }} -ntp"
